---
# tasks file for ansible-vim
- name: Deploy vim dotfiles repo
  git:
    repo: git@github.com:binaryplease/dotfiles-vim.git
    dest: /home/{{user}}/binaryplease/.vim

- name: Set vim colorscheme
  template:
    src: vimrc_background.j2
    dest: /home/{{user}}/.vimrc_background

- name: Create symbolic link for neovim
  file:
    src: "/home/{{user}}/.vim"
    dest: "/home/{{user}}/.config/nvim"
    state: link

- name: Make sure .local/share/applications exists
  file:
    path: /home/{{user}}/.local/share/applications
    state: directory

- name: Copy nvim.desktop
  copy:
    src: nvim.desktop
    dest: "/home/{{user}}/.local/share/applications/nvim.desktop

