---
# tasks file for ansible-vim
- name: Deploy vim dotfiles repo
  git:
    repo: git@github.com:binaryplease/dotfiles-vim.git
    dest: /home/{{user}}/binaryplease

- name: Set vim colorscheme
  template:
    src: vimrc_background.j2
    dest: /home/{{user}}/.vimrc_background
